name: release
description: release ghr
inputs:
  token:
    description: GitHub token
    required: true
  tag:
    description: Git tag for the release
    required: false
runs:
  using: composite
  steps:
  - name: setup go
    uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
    with:
      go-version-file: go.mod
  - name: release
    run: make release
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
  - name: update semver tag
    uses: haya14busa/action-update-semver@7d2c558640ea49e798d46539536190aff8c18715 # v1.5.1
    with:
      major_version_tag_only: true
      tag: ${{ inputs.tag }}
      github_token: ${{ inputs.token }}
